---
title: "Instructions"
---

I created this website to prep for office hours, mainly to practice setting it up in Positron.

1. Open a Positron folder in the general folder where you'd like to set up your website. For example: Desktop, Documents, Downloads, etc.

2. Open the terminal (shortcut: Control + backtick (`)).

    - Type and enter: `quarto create project website`
    - Enter your desired website name: `first-last.github.io`
    - Enter the title: `First Last`

3. Publish the folder to a public GitHub repository via Positron. Commit, pull, and push as you make changes to your website.

4. You now have a couple of new files. `index.qmd` is the homepage, `about.qmd` is the About page, and `_quarto.yml` is essentially the blueprint for the website. You can also edit `index.qmd` and `about.qmd` to your liking. You can also create new `.qmd` files for additional pages and add them to `_quarto.yml`. 

5. Add any desired documents (resume, photos, posters, presentation slides, etc.) to this new folder. These documents can be placed in a subfolder named `files`.

6. Click the **Preview** button to see what your website looks like.

7. When you're ready to publish your website, follow the steps in this helpful [link](https://quarto.org/docs/publishing/github-pages.html) to publish your website to GitHub Pages. Essentially, do the following:

    - Add `output-dir: docs` to the `_quarto.yml` file under `type: website`.

    - Now work in the terminal:

        - Add a `.nojekyll` file to the root of your repository:

            - Mac/Linux: `touch .nojekyll`
            - Windows: `copy NUL .nojekyll`

        - Run the following in the terminal:

            ```bash
            quarto render
            git add docs
            git commit -m "Publish site to docs/"
            git push
            ```

    - Finally, configure your GitHub repository to publish from the `docs` directory of your `main` branch. On github.com, go to the **Settings** tab of your GitHub repository, then **Pages**. Select `main` as the branch and `/docs` as the folder. Click **Save**.

8. Refresh and view your deployed website. It may take a few minutes for the website or new changes to appear.

9. **KEY:** Every time you make a change to your website, you must hit the Preview button and then commit and push those changes so that the HTML is updated. The changes will not be reflected on your website until you do this. It may take a few minutes for the changes to appear. Just refresh.